spring:
    application:
        name: glig
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:app
        driver-class-name: org.h2.Driver
        username: sa
        password: password
