spring:
    application:
        name: glig
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:app
        driver-class-name: org.h2.Driver
        username: sa
        password: password
okta:
    oauth2:
        issuer: https://jk-projects.eu.auth0.com
        audience: https://glig.com
logging:
    level:
        root: info
