/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicAboutServiceRouteImport } from './routes/_public/about-service'
import { Route as AuthenticatedWorkerRouteImport } from './routes/_authenticated/worker'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedWorkerIndexRouteImport } from './routes/_authenticated/worker/index'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer/index'
import { Route as AuthenticatedWorkerTasksIndexRouteImport } from './routes/_authenticated/worker/tasks/index'
import { Route as AuthenticatedWorkerOwnTasksIndexRouteImport } from './routes/_authenticated/worker/own-tasks/index'
import { Route as AuthenticatedWorkerMyProfileIndexRouteImport } from './routes/_authenticated/worker/my-profile/index'
import { Route as AuthenticatedWorkerMyApplicationsIndexRouteImport } from './routes/_authenticated/worker/my-applications/index'
import { Route as AuthenticatedWorkerDashboardIndexRouteImport } from './routes/_authenticated/worker/dashboard/index'
import { Route as AuthenticatedEmployerMyTasksIndexRouteImport } from './routes/_authenticated/employer/my-tasks/index'
import { Route as AuthenticatedEmployerMyProflieIndexRouteImport } from './routes/_authenticated/employer/my-proflie/index'
import { Route as AuthenticatedEmployerCreateTaskIndexRouteImport } from './routes/_authenticated/employer/create-task/index'
import { Route as AuthenticatedWorkerTasksTaskIdRouteImport } from './routes/_authenticated/worker/tasks/$taskId'
import { Route as AuthenticatedEmployerCreateTaskPublicTaskRouteImport } from './routes/_authenticated/employer/create-task/public-task'
import { Route as AuthenticatedEmployerCreateTaskJobOfferRouteImport } from './routes/_authenticated/employer/create-task/job-offer'
import { Route as AuthenticatedWorkerOwnTasksWaitingApprovalIndexRouteImport } from './routes/_authenticated/worker/own-tasks/waiting-approval/index'
import { Route as AuthenticatedWorkerOwnTasksToDoIndexRouteImport } from './routes/_authenticated/worker/own-tasks/to-do/index'
import { Route as AuthenticatedWorkerOwnTasksPastIndexRouteImport } from './routes/_authenticated/worker/own-tasks/past/index'
import { Route as AuthenticatedWorkerMyProfileReviewsIndexRouteImport } from './routes/_authenticated/worker/my-profile/reviews/index'
import { Route as AuthenticatedWorkerMyProfileDetailsIndexRouteImport } from './routes/_authenticated/worker/my-profile/details/index'
import { Route as AuthenticatedWorkerMyApplicationsPastIndexRouteImport } from './routes/_authenticated/worker/my-applications/past/index'
import { Route as AuthenticatedWorkerMyApplicationsActiveIndexRouteImport } from './routes/_authenticated/worker/my-applications/active/index'
import { Route as AuthenticatedWorkerMyApplicationsTaskIdIndexRouteImport } from './routes/_authenticated/worker/my-applications/$taskId/index'
import { Route as AuthenticatedWorkerDashboardPaymentsIndexRouteImport } from './routes/_authenticated/worker/dashboard/payments/index'
import { Route as AuthenticatedEmployerMyProflieReviewsIndexRouteImport } from './routes/_authenticated/employer/my-proflie/reviews/index'
import { Route as AuthenticatedEmployerMyProfliePaymentsIndexRouteImport } from './routes/_authenticated/employer/my-proflie/payments/index'
import { Route as AuthenticatedEmployerMyProflieDetailsIndexRouteImport } from './routes/_authenticated/employer/my-proflie/details/index'
import { Route as AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRouteImport } from './routes/_authenticated/worker/own-tasks/waiting-approval/$taskId'
import { Route as AuthenticatedWorkerOwnTasksToDoTaskIdRouteImport } from './routes/_authenticated/worker/own-tasks/to-do/$taskId'
import { Route as AuthenticatedWorkerOwnTasksPastTaskIdRouteImport } from './routes/_authenticated/worker/own-tasks/past/$taskId'
import { Route as AuthenticatedWorkerMyProfileReviewsReviewIdRouteImport } from './routes/_authenticated/worker/my-profile/reviews/$reviewId'
import { Route as AuthenticatedWorkerMyProfileDetailsEditRouteImport } from './routes/_authenticated/worker/my-profile/details/edit'
import { Route as AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRouteImport } from './routes/_authenticated/worker/my-applications/$taskId/task-details'
import { Route as AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRouteImport } from './routes/_authenticated/worker/my-applications/$taskId/application-details'
import { Route as AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRouteImport } from './routes/_authenticated/worker/dashboard/payments/$paymentTransactionId'
import { Route as AuthenticatedEmployerMyProflieReviewsReviewIdRouteImport } from './routes/_authenticated/employer/my-proflie/reviews/$reviewId'
import { Route as AuthenticatedEmployerMyProfliePaymentsPaymentIdRouteImport } from './routes/_authenticated/employer/my-proflie/payments/$paymentId'
import { Route as AuthenticatedEmployerMyProflieDetailsEditRouteImport } from './routes/_authenticated/employer/my-proflie/details/edit'
import { Route as AuthenticatedEmployerMyTasksTaskIdTsxIndexRouteImport } from './routes/_authenticated/employer/my-tasks/$taskId.tsx/index'
import { Route as AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRouteImport } from './routes/_authenticated/employer/my-tasks/$taskId.tsx/details/index'
import { Route as AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRouteImport } from './routes/_authenticated/employer/my-tasks/$taskId.tsx/applcations/index'
import { Route as AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRouteImport } from './routes/_authenticated/employer/my-tasks/$taskId.tsx/details/edit'
import { Route as AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRouteImport } from './routes/_authenticated/employer/my-tasks/$taskId.tsx/applcations/$username'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutServiceRoute = PublicAboutServiceRouteImport.update({
  id: '/about-service',
  path: '/about-service',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedWorkerRoute = AuthenticatedWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkerIndexRoute =
  AuthenticatedWorkerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedWorkerTasksIndexRoute =
  AuthenticatedWorkerTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerOwnTasksIndexRoute =
  AuthenticatedWorkerOwnTasksIndexRouteImport.update({
    id: '/own-tasks/',
    path: '/own-tasks/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyProfileIndexRoute =
  AuthenticatedWorkerMyProfileIndexRouteImport.update({
    id: '/my-profile/',
    path: '/my-profile/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyApplicationsIndexRoute =
  AuthenticatedWorkerMyApplicationsIndexRouteImport.update({
    id: '/my-applications/',
    path: '/my-applications/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerDashboardIndexRoute =
  AuthenticatedWorkerDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedEmployerMyTasksIndexRoute =
  AuthenticatedEmployerMyTasksIndexRouteImport.update({
    id: '/my-tasks/',
    path: '/my-tasks/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyProflieIndexRoute =
  AuthenticatedEmployerMyProflieIndexRouteImport.update({
    id: '/my-proflie/',
    path: '/my-proflie/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerCreateTaskIndexRoute =
  AuthenticatedEmployerCreateTaskIndexRouteImport.update({
    id: '/create-task/',
    path: '/create-task/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedWorkerTasksTaskIdRoute =
  AuthenticatedWorkerTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedEmployerCreateTaskPublicTaskRoute =
  AuthenticatedEmployerCreateTaskPublicTaskRouteImport.update({
    id: '/create-task/public-task',
    path: '/create-task/public-task',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerCreateTaskJobOfferRoute =
  AuthenticatedEmployerCreateTaskJobOfferRouteImport.update({
    id: '/create-task/job-offer',
    path: '/create-task/job-offer',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedWorkerOwnTasksWaitingApprovalIndexRoute =
  AuthenticatedWorkerOwnTasksWaitingApprovalIndexRouteImport.update({
    id: '/own-tasks/waiting-approval/',
    path: '/own-tasks/waiting-approval/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerOwnTasksToDoIndexRoute =
  AuthenticatedWorkerOwnTasksToDoIndexRouteImport.update({
    id: '/own-tasks/to-do/',
    path: '/own-tasks/to-do/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerOwnTasksPastIndexRoute =
  AuthenticatedWorkerOwnTasksPastIndexRouteImport.update({
    id: '/own-tasks/past/',
    path: '/own-tasks/past/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyProfileReviewsIndexRoute =
  AuthenticatedWorkerMyProfileReviewsIndexRouteImport.update({
    id: '/my-profile/reviews/',
    path: '/my-profile/reviews/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyProfileDetailsIndexRoute =
  AuthenticatedWorkerMyProfileDetailsIndexRouteImport.update({
    id: '/my-profile/details/',
    path: '/my-profile/details/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyApplicationsPastIndexRoute =
  AuthenticatedWorkerMyApplicationsPastIndexRouteImport.update({
    id: '/my-applications/past/',
    path: '/my-applications/past/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyApplicationsActiveIndexRoute =
  AuthenticatedWorkerMyApplicationsActiveIndexRouteImport.update({
    id: '/my-applications/active/',
    path: '/my-applications/active/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyApplicationsTaskIdIndexRoute =
  AuthenticatedWorkerMyApplicationsTaskIdIndexRouteImport.update({
    id: '/my-applications/$taskId/',
    path: '/my-applications/$taskId/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerDashboardPaymentsIndexRoute =
  AuthenticatedWorkerDashboardPaymentsIndexRouteImport.update({
    id: '/dashboard/payments/',
    path: '/dashboard/payments/',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedEmployerMyProflieReviewsIndexRoute =
  AuthenticatedEmployerMyProflieReviewsIndexRouteImport.update({
    id: '/my-proflie/reviews/',
    path: '/my-proflie/reviews/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyProfliePaymentsIndexRoute =
  AuthenticatedEmployerMyProfliePaymentsIndexRouteImport.update({
    id: '/my-proflie/payments/',
    path: '/my-proflie/payments/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyProflieDetailsIndexRoute =
  AuthenticatedEmployerMyProflieDetailsIndexRouteImport.update({
    id: '/my-proflie/details/',
    path: '/my-proflie/details/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRoute =
  AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRouteImport.update({
    id: '/own-tasks/waiting-approval/$taskId',
    path: '/own-tasks/waiting-approval/$taskId',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerOwnTasksToDoTaskIdRoute =
  AuthenticatedWorkerOwnTasksToDoTaskIdRouteImport.update({
    id: '/own-tasks/to-do/$taskId',
    path: '/own-tasks/to-do/$taskId',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerOwnTasksPastTaskIdRoute =
  AuthenticatedWorkerOwnTasksPastTaskIdRouteImport.update({
    id: '/own-tasks/past/$taskId',
    path: '/own-tasks/past/$taskId',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyProfileReviewsReviewIdRoute =
  AuthenticatedWorkerMyProfileReviewsReviewIdRouteImport.update({
    id: '/my-profile/reviews/$reviewId',
    path: '/my-profile/reviews/$reviewId',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyProfileDetailsEditRoute =
  AuthenticatedWorkerMyProfileDetailsEditRouteImport.update({
    id: '/my-profile/details/edit',
    path: '/my-profile/details/edit',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRoute =
  AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRouteImport.update({
    id: '/my-applications/$taskId/task-details',
    path: '/my-applications/$taskId/task-details',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRoute =
  AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRouteImport.update({
    id: '/my-applications/$taskId/application-details',
    path: '/my-applications/$taskId/application-details',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRoute =
  AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRouteImport.update({
    id: '/dashboard/payments/$paymentTransactionId',
    path: '/dashboard/payments/$paymentTransactionId',
    getParentRoute: () => AuthenticatedWorkerRoute,
  } as any)
const AuthenticatedEmployerMyProflieReviewsReviewIdRoute =
  AuthenticatedEmployerMyProflieReviewsReviewIdRouteImport.update({
    id: '/my-proflie/reviews/$reviewId',
    path: '/my-proflie/reviews/$reviewId',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyProfliePaymentsPaymentIdRoute =
  AuthenticatedEmployerMyProfliePaymentsPaymentIdRouteImport.update({
    id: '/my-proflie/payments/$paymentId',
    path: '/my-proflie/payments/$paymentId',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyProflieDetailsEditRoute =
  AuthenticatedEmployerMyProflieDetailsEditRouteImport.update({
    id: '/my-proflie/details/edit',
    path: '/my-proflie/details/edit',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyTasksTaskIdTsxIndexRoute =
  AuthenticatedEmployerMyTasksTaskIdTsxIndexRouteImport.update({
    id: '/my-tasks/$taskId/tsx/',
    path: '/my-tasks/$taskId/tsx/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRoute =
  AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRouteImport.update({
    id: '/my-tasks/$taskId/tsx/details/',
    path: '/my-tasks/$taskId/tsx/details/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRoute =
  AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRouteImport.update({
    id: '/my-tasks/$taskId/tsx/applcations/',
    path: '/my-tasks/$taskId/tsx/applcations/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRoute =
  AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRouteImport.update({
    id: '/my-tasks/$taskId/tsx/details/edit',
    path: '/my-tasks/$taskId/tsx/details/edit',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRoute =
  AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRouteImport.update({
    id: '/my-tasks/$taskId/tsx/applcations/$username',
    path: '/my-tasks/$taskId/tsx/applcations/$username',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/worker': typeof AuthenticatedWorkerRouteWithChildren
  '/about-service': typeof PublicAboutServiceRoute
  '/faq': typeof PublicFaqRoute
  '/pricing': typeof PublicPricingRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/worker/': typeof AuthenticatedWorkerIndexRoute
  '/employer/create-task/job-offer': typeof AuthenticatedEmployerCreateTaskJobOfferRoute
  '/employer/create-task/public-task': typeof AuthenticatedEmployerCreateTaskPublicTaskRoute
  '/worker/tasks/$taskId': typeof AuthenticatedWorkerTasksTaskIdRoute
  '/employer/create-task': typeof AuthenticatedEmployerCreateTaskIndexRoute
  '/employer/my-proflie': typeof AuthenticatedEmployerMyProflieIndexRoute
  '/employer/my-tasks': typeof AuthenticatedEmployerMyTasksIndexRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardIndexRoute
  '/worker/my-applications': typeof AuthenticatedWorkerMyApplicationsIndexRoute
  '/worker/my-profile': typeof AuthenticatedWorkerMyProfileIndexRoute
  '/worker/own-tasks': typeof AuthenticatedWorkerOwnTasksIndexRoute
  '/worker/tasks': typeof AuthenticatedWorkerTasksIndexRoute
  '/employer/my-proflie/details/edit': typeof AuthenticatedEmployerMyProflieDetailsEditRoute
  '/employer/my-proflie/payments/$paymentId': typeof AuthenticatedEmployerMyProfliePaymentsPaymentIdRoute
  '/employer/my-proflie/reviews/$reviewId': typeof AuthenticatedEmployerMyProflieReviewsReviewIdRoute
  '/worker/dashboard/payments/$paymentTransactionId': typeof AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRoute
  '/worker/my-applications/$taskId/application-details': typeof AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRoute
  '/worker/my-applications/$taskId/task-details': typeof AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRoute
  '/worker/my-profile/details/edit': typeof AuthenticatedWorkerMyProfileDetailsEditRoute
  '/worker/my-profile/reviews/$reviewId': typeof AuthenticatedWorkerMyProfileReviewsReviewIdRoute
  '/worker/own-tasks/past/$taskId': typeof AuthenticatedWorkerOwnTasksPastTaskIdRoute
  '/worker/own-tasks/to-do/$taskId': typeof AuthenticatedWorkerOwnTasksToDoTaskIdRoute
  '/worker/own-tasks/waiting-approval/$taskId': typeof AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRoute
  '/employer/my-proflie/details': typeof AuthenticatedEmployerMyProflieDetailsIndexRoute
  '/employer/my-proflie/payments': typeof AuthenticatedEmployerMyProfliePaymentsIndexRoute
  '/employer/my-proflie/reviews': typeof AuthenticatedEmployerMyProflieReviewsIndexRoute
  '/worker/dashboard/payments': typeof AuthenticatedWorkerDashboardPaymentsIndexRoute
  '/worker/my-applications/$taskId': typeof AuthenticatedWorkerMyApplicationsTaskIdIndexRoute
  '/worker/my-applications/active': typeof AuthenticatedWorkerMyApplicationsActiveIndexRoute
  '/worker/my-applications/past': typeof AuthenticatedWorkerMyApplicationsPastIndexRoute
  '/worker/my-profile/details': typeof AuthenticatedWorkerMyProfileDetailsIndexRoute
  '/worker/my-profile/reviews': typeof AuthenticatedWorkerMyProfileReviewsIndexRoute
  '/worker/own-tasks/past': typeof AuthenticatedWorkerOwnTasksPastIndexRoute
  '/worker/own-tasks/to-do': typeof AuthenticatedWorkerOwnTasksToDoIndexRoute
  '/worker/own-tasks/waiting-approval': typeof AuthenticatedWorkerOwnTasksWaitingApprovalIndexRoute
  '/employer/my-tasks/$taskId/tsx': typeof AuthenticatedEmployerMyTasksTaskIdTsxIndexRoute
  '/employer/my-tasks/$taskId/tsx/applcations/$username': typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRoute
  '/employer/my-tasks/$taskId/tsx/details/edit': typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRoute
  '/employer/my-tasks/$taskId/tsx/applcations': typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRoute
  '/employer/my-tasks/$taskId/tsx/details': typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-service': typeof PublicAboutServiceRoute
  '/faq': typeof PublicFaqRoute
  '/pricing': typeof PublicPricingRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/worker': typeof AuthenticatedWorkerIndexRoute
  '/employer/create-task/job-offer': typeof AuthenticatedEmployerCreateTaskJobOfferRoute
  '/employer/create-task/public-task': typeof AuthenticatedEmployerCreateTaskPublicTaskRoute
  '/worker/tasks/$taskId': typeof AuthenticatedWorkerTasksTaskIdRoute
  '/employer/create-task': typeof AuthenticatedEmployerCreateTaskIndexRoute
  '/employer/my-proflie': typeof AuthenticatedEmployerMyProflieIndexRoute
  '/employer/my-tasks': typeof AuthenticatedEmployerMyTasksIndexRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardIndexRoute
  '/worker/my-applications': typeof AuthenticatedWorkerMyApplicationsIndexRoute
  '/worker/my-profile': typeof AuthenticatedWorkerMyProfileIndexRoute
  '/worker/own-tasks': typeof AuthenticatedWorkerOwnTasksIndexRoute
  '/worker/tasks': typeof AuthenticatedWorkerTasksIndexRoute
  '/employer/my-proflie/details/edit': typeof AuthenticatedEmployerMyProflieDetailsEditRoute
  '/employer/my-proflie/payments/$paymentId': typeof AuthenticatedEmployerMyProfliePaymentsPaymentIdRoute
  '/employer/my-proflie/reviews/$reviewId': typeof AuthenticatedEmployerMyProflieReviewsReviewIdRoute
  '/worker/dashboard/payments/$paymentTransactionId': typeof AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRoute
  '/worker/my-applications/$taskId/application-details': typeof AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRoute
  '/worker/my-applications/$taskId/task-details': typeof AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRoute
  '/worker/my-profile/details/edit': typeof AuthenticatedWorkerMyProfileDetailsEditRoute
  '/worker/my-profile/reviews/$reviewId': typeof AuthenticatedWorkerMyProfileReviewsReviewIdRoute
  '/worker/own-tasks/past/$taskId': typeof AuthenticatedWorkerOwnTasksPastTaskIdRoute
  '/worker/own-tasks/to-do/$taskId': typeof AuthenticatedWorkerOwnTasksToDoTaskIdRoute
  '/worker/own-tasks/waiting-approval/$taskId': typeof AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRoute
  '/employer/my-proflie/details': typeof AuthenticatedEmployerMyProflieDetailsIndexRoute
  '/employer/my-proflie/payments': typeof AuthenticatedEmployerMyProfliePaymentsIndexRoute
  '/employer/my-proflie/reviews': typeof AuthenticatedEmployerMyProflieReviewsIndexRoute
  '/worker/dashboard/payments': typeof AuthenticatedWorkerDashboardPaymentsIndexRoute
  '/worker/my-applications/$taskId': typeof AuthenticatedWorkerMyApplicationsTaskIdIndexRoute
  '/worker/my-applications/active': typeof AuthenticatedWorkerMyApplicationsActiveIndexRoute
  '/worker/my-applications/past': typeof AuthenticatedWorkerMyApplicationsPastIndexRoute
  '/worker/my-profile/details': typeof AuthenticatedWorkerMyProfileDetailsIndexRoute
  '/worker/my-profile/reviews': typeof AuthenticatedWorkerMyProfileReviewsIndexRoute
  '/worker/own-tasks/past': typeof AuthenticatedWorkerOwnTasksPastIndexRoute
  '/worker/own-tasks/to-do': typeof AuthenticatedWorkerOwnTasksToDoIndexRoute
  '/worker/own-tasks/waiting-approval': typeof AuthenticatedWorkerOwnTasksWaitingApprovalIndexRoute
  '/employer/my-tasks/$taskId/tsx': typeof AuthenticatedEmployerMyTasksTaskIdTsxIndexRoute
  '/employer/my-tasks/$taskId/tsx/applcations/$username': typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRoute
  '/employer/my-tasks/$taskId/tsx/details/edit': typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRoute
  '/employer/my-tasks/$taskId/tsx/applcations': typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRoute
  '/employer/my-tasks/$taskId/tsx/details': typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/_authenticated/worker': typeof AuthenticatedWorkerRouteWithChildren
  '/_public/about-service': typeof PublicAboutServiceRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/worker/': typeof AuthenticatedWorkerIndexRoute
  '/_authenticated/employer/create-task/job-offer': typeof AuthenticatedEmployerCreateTaskJobOfferRoute
  '/_authenticated/employer/create-task/public-task': typeof AuthenticatedEmployerCreateTaskPublicTaskRoute
  '/_authenticated/worker/tasks/$taskId': typeof AuthenticatedWorkerTasksTaskIdRoute
  '/_authenticated/employer/create-task/': typeof AuthenticatedEmployerCreateTaskIndexRoute
  '/_authenticated/employer/my-proflie/': typeof AuthenticatedEmployerMyProflieIndexRoute
  '/_authenticated/employer/my-tasks/': typeof AuthenticatedEmployerMyTasksIndexRoute
  '/_authenticated/worker/dashboard/': typeof AuthenticatedWorkerDashboardIndexRoute
  '/_authenticated/worker/my-applications/': typeof AuthenticatedWorkerMyApplicationsIndexRoute
  '/_authenticated/worker/my-profile/': typeof AuthenticatedWorkerMyProfileIndexRoute
  '/_authenticated/worker/own-tasks/': typeof AuthenticatedWorkerOwnTasksIndexRoute
  '/_authenticated/worker/tasks/': typeof AuthenticatedWorkerTasksIndexRoute
  '/_authenticated/employer/my-proflie/details/edit': typeof AuthenticatedEmployerMyProflieDetailsEditRoute
  '/_authenticated/employer/my-proflie/payments/$paymentId': typeof AuthenticatedEmployerMyProfliePaymentsPaymentIdRoute
  '/_authenticated/employer/my-proflie/reviews/$reviewId': typeof AuthenticatedEmployerMyProflieReviewsReviewIdRoute
  '/_authenticated/worker/dashboard/payments/$paymentTransactionId': typeof AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRoute
  '/_authenticated/worker/my-applications/$taskId/application-details': typeof AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRoute
  '/_authenticated/worker/my-applications/$taskId/task-details': typeof AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRoute
  '/_authenticated/worker/my-profile/details/edit': typeof AuthenticatedWorkerMyProfileDetailsEditRoute
  '/_authenticated/worker/my-profile/reviews/$reviewId': typeof AuthenticatedWorkerMyProfileReviewsReviewIdRoute
  '/_authenticated/worker/own-tasks/past/$taskId': typeof AuthenticatedWorkerOwnTasksPastTaskIdRoute
  '/_authenticated/worker/own-tasks/to-do/$taskId': typeof AuthenticatedWorkerOwnTasksToDoTaskIdRoute
  '/_authenticated/worker/own-tasks/waiting-approval/$taskId': typeof AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRoute
  '/_authenticated/employer/my-proflie/details/': typeof AuthenticatedEmployerMyProflieDetailsIndexRoute
  '/_authenticated/employer/my-proflie/payments/': typeof AuthenticatedEmployerMyProfliePaymentsIndexRoute
  '/_authenticated/employer/my-proflie/reviews/': typeof AuthenticatedEmployerMyProflieReviewsIndexRoute
  '/_authenticated/worker/dashboard/payments/': typeof AuthenticatedWorkerDashboardPaymentsIndexRoute
  '/_authenticated/worker/my-applications/$taskId/': typeof AuthenticatedWorkerMyApplicationsTaskIdIndexRoute
  '/_authenticated/worker/my-applications/active/': typeof AuthenticatedWorkerMyApplicationsActiveIndexRoute
  '/_authenticated/worker/my-applications/past/': typeof AuthenticatedWorkerMyApplicationsPastIndexRoute
  '/_authenticated/worker/my-profile/details/': typeof AuthenticatedWorkerMyProfileDetailsIndexRoute
  '/_authenticated/worker/my-profile/reviews/': typeof AuthenticatedWorkerMyProfileReviewsIndexRoute
  '/_authenticated/worker/own-tasks/past/': typeof AuthenticatedWorkerOwnTasksPastIndexRoute
  '/_authenticated/worker/own-tasks/to-do/': typeof AuthenticatedWorkerOwnTasksToDoIndexRoute
  '/_authenticated/worker/own-tasks/waiting-approval/': typeof AuthenticatedWorkerOwnTasksWaitingApprovalIndexRoute
  '/_authenticated/employer/my-tasks/$taskId/tsx/': typeof AuthenticatedEmployerMyTasksTaskIdTsxIndexRoute
  '/_authenticated/employer/my-tasks/$taskId/tsx/applcations/$username': typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRoute
  '/_authenticated/employer/my-tasks/$taskId/tsx/details/edit': typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRoute
  '/_authenticated/employer/my-tasks/$taskId/tsx/applcations/': typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRoute
  '/_authenticated/employer/my-tasks/$taskId/tsx/details/': typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employer'
    | '/worker'
    | '/about-service'
    | '/faq'
    | '/pricing'
    | '/employer/'
    | '/worker/'
    | '/employer/create-task/job-offer'
    | '/employer/create-task/public-task'
    | '/worker/tasks/$taskId'
    | '/employer/create-task'
    | '/employer/my-proflie'
    | '/employer/my-tasks'
    | '/worker/dashboard'
    | '/worker/my-applications'
    | '/worker/my-profile'
    | '/worker/own-tasks'
    | '/worker/tasks'
    | '/employer/my-proflie/details/edit'
    | '/employer/my-proflie/payments/$paymentId'
    | '/employer/my-proflie/reviews/$reviewId'
    | '/worker/dashboard/payments/$paymentTransactionId'
    | '/worker/my-applications/$taskId/application-details'
    | '/worker/my-applications/$taskId/task-details'
    | '/worker/my-profile/details/edit'
    | '/worker/my-profile/reviews/$reviewId'
    | '/worker/own-tasks/past/$taskId'
    | '/worker/own-tasks/to-do/$taskId'
    | '/worker/own-tasks/waiting-approval/$taskId'
    | '/employer/my-proflie/details'
    | '/employer/my-proflie/payments'
    | '/employer/my-proflie/reviews'
    | '/worker/dashboard/payments'
    | '/worker/my-applications/$taskId'
    | '/worker/my-applications/active'
    | '/worker/my-applications/past'
    | '/worker/my-profile/details'
    | '/worker/my-profile/reviews'
    | '/worker/own-tasks/past'
    | '/worker/own-tasks/to-do'
    | '/worker/own-tasks/waiting-approval'
    | '/employer/my-tasks/$taskId/tsx'
    | '/employer/my-tasks/$taskId/tsx/applcations/$username'
    | '/employer/my-tasks/$taskId/tsx/details/edit'
    | '/employer/my-tasks/$taskId/tsx/applcations'
    | '/employer/my-tasks/$taskId/tsx/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-service'
    | '/faq'
    | '/pricing'
    | '/employer'
    | '/worker'
    | '/employer/create-task/job-offer'
    | '/employer/create-task/public-task'
    | '/worker/tasks/$taskId'
    | '/employer/create-task'
    | '/employer/my-proflie'
    | '/employer/my-tasks'
    | '/worker/dashboard'
    | '/worker/my-applications'
    | '/worker/my-profile'
    | '/worker/own-tasks'
    | '/worker/tasks'
    | '/employer/my-proflie/details/edit'
    | '/employer/my-proflie/payments/$paymentId'
    | '/employer/my-proflie/reviews/$reviewId'
    | '/worker/dashboard/payments/$paymentTransactionId'
    | '/worker/my-applications/$taskId/application-details'
    | '/worker/my-applications/$taskId/task-details'
    | '/worker/my-profile/details/edit'
    | '/worker/my-profile/reviews/$reviewId'
    | '/worker/own-tasks/past/$taskId'
    | '/worker/own-tasks/to-do/$taskId'
    | '/worker/own-tasks/waiting-approval/$taskId'
    | '/employer/my-proflie/details'
    | '/employer/my-proflie/payments'
    | '/employer/my-proflie/reviews'
    | '/worker/dashboard/payments'
    | '/worker/my-applications/$taskId'
    | '/worker/my-applications/active'
    | '/worker/my-applications/past'
    | '/worker/my-profile/details'
    | '/worker/my-profile/reviews'
    | '/worker/own-tasks/past'
    | '/worker/own-tasks/to-do'
    | '/worker/own-tasks/waiting-approval'
    | '/employer/my-tasks/$taskId/tsx'
    | '/employer/my-tasks/$taskId/tsx/applcations/$username'
    | '/employer/my-tasks/$taskId/tsx/details/edit'
    | '/employer/my-tasks/$taskId/tsx/applcations'
    | '/employer/my-tasks/$taskId/tsx/details'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/employer'
    | '/_authenticated/worker'
    | '/_public/about-service'
    | '/_public/faq'
    | '/_public/pricing'
    | '/_authenticated/employer/'
    | '/_authenticated/worker/'
    | '/_authenticated/employer/create-task/job-offer'
    | '/_authenticated/employer/create-task/public-task'
    | '/_authenticated/worker/tasks/$taskId'
    | '/_authenticated/employer/create-task/'
    | '/_authenticated/employer/my-proflie/'
    | '/_authenticated/employer/my-tasks/'
    | '/_authenticated/worker/dashboard/'
    | '/_authenticated/worker/my-applications/'
    | '/_authenticated/worker/my-profile/'
    | '/_authenticated/worker/own-tasks/'
    | '/_authenticated/worker/tasks/'
    | '/_authenticated/employer/my-proflie/details/edit'
    | '/_authenticated/employer/my-proflie/payments/$paymentId'
    | '/_authenticated/employer/my-proflie/reviews/$reviewId'
    | '/_authenticated/worker/dashboard/payments/$paymentTransactionId'
    | '/_authenticated/worker/my-applications/$taskId/application-details'
    | '/_authenticated/worker/my-applications/$taskId/task-details'
    | '/_authenticated/worker/my-profile/details/edit'
    | '/_authenticated/worker/my-profile/reviews/$reviewId'
    | '/_authenticated/worker/own-tasks/past/$taskId'
    | '/_authenticated/worker/own-tasks/to-do/$taskId'
    | '/_authenticated/worker/own-tasks/waiting-approval/$taskId'
    | '/_authenticated/employer/my-proflie/details/'
    | '/_authenticated/employer/my-proflie/payments/'
    | '/_authenticated/employer/my-proflie/reviews/'
    | '/_authenticated/worker/dashboard/payments/'
    | '/_authenticated/worker/my-applications/$taskId/'
    | '/_authenticated/worker/my-applications/active/'
    | '/_authenticated/worker/my-applications/past/'
    | '/_authenticated/worker/my-profile/details/'
    | '/_authenticated/worker/my-profile/reviews/'
    | '/_authenticated/worker/own-tasks/past/'
    | '/_authenticated/worker/own-tasks/to-do/'
    | '/_authenticated/worker/own-tasks/waiting-approval/'
    | '/_authenticated/employer/my-tasks/$taskId/tsx/'
    | '/_authenticated/employer/my-tasks/$taskId/tsx/applcations/$username'
    | '/_authenticated/employer/my-tasks/$taskId/tsx/details/edit'
    | '/_authenticated/employer/my-tasks/$taskId/tsx/applcations/'
    | '/_authenticated/employer/my-tasks/$taskId/tsx/details/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about-service': {
      id: '/_public/about-service'
      path: '/about-service'
      fullPath: '/about-service'
      preLoaderRoute: typeof PublicAboutServiceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/worker': {
      id: '/_authenticated/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof AuthenticatedWorkerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/worker/': {
      id: '/_authenticated/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof AuthenticatedWorkerIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/worker/tasks/': {
      id: '/_authenticated/worker/tasks/'
      path: '/tasks'
      fullPath: '/worker/tasks'
      preLoaderRoute: typeof AuthenticatedWorkerTasksIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/own-tasks/': {
      id: '/_authenticated/worker/own-tasks/'
      path: '/own-tasks'
      fullPath: '/worker/own-tasks'
      preLoaderRoute: typeof AuthenticatedWorkerOwnTasksIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-profile/': {
      id: '/_authenticated/worker/my-profile/'
      path: '/my-profile'
      fullPath: '/worker/my-profile'
      preLoaderRoute: typeof AuthenticatedWorkerMyProfileIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-applications/': {
      id: '/_authenticated/worker/my-applications/'
      path: '/my-applications'
      fullPath: '/worker/my-applications'
      preLoaderRoute: typeof AuthenticatedWorkerMyApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/dashboard/': {
      id: '/_authenticated/worker/dashboard/'
      path: '/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof AuthenticatedWorkerDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/employer/my-tasks/': {
      id: '/_authenticated/employer/my-tasks/'
      path: '/my-tasks'
      fullPath: '/employer/my-tasks'
      preLoaderRoute: typeof AuthenticatedEmployerMyTasksIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-proflie/': {
      id: '/_authenticated/employer/my-proflie/'
      path: '/my-proflie'
      fullPath: '/employer/my-proflie'
      preLoaderRoute: typeof AuthenticatedEmployerMyProflieIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/create-task/': {
      id: '/_authenticated/employer/create-task/'
      path: '/create-task'
      fullPath: '/employer/create-task'
      preLoaderRoute: typeof AuthenticatedEmployerCreateTaskIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/worker/tasks/$taskId': {
      id: '/_authenticated/worker/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/worker/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkerTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/employer/create-task/public-task': {
      id: '/_authenticated/employer/create-task/public-task'
      path: '/create-task/public-task'
      fullPath: '/employer/create-task/public-task'
      preLoaderRoute: typeof AuthenticatedEmployerCreateTaskPublicTaskRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/create-task/job-offer': {
      id: '/_authenticated/employer/create-task/job-offer'
      path: '/create-task/job-offer'
      fullPath: '/employer/create-task/job-offer'
      preLoaderRoute: typeof AuthenticatedEmployerCreateTaskJobOfferRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/worker/own-tasks/waiting-approval/': {
      id: '/_authenticated/worker/own-tasks/waiting-approval/'
      path: '/own-tasks/waiting-approval'
      fullPath: '/worker/own-tasks/waiting-approval'
      preLoaderRoute: typeof AuthenticatedWorkerOwnTasksWaitingApprovalIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/own-tasks/to-do/': {
      id: '/_authenticated/worker/own-tasks/to-do/'
      path: '/own-tasks/to-do'
      fullPath: '/worker/own-tasks/to-do'
      preLoaderRoute: typeof AuthenticatedWorkerOwnTasksToDoIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/own-tasks/past/': {
      id: '/_authenticated/worker/own-tasks/past/'
      path: '/own-tasks/past'
      fullPath: '/worker/own-tasks/past'
      preLoaderRoute: typeof AuthenticatedWorkerOwnTasksPastIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-profile/reviews/': {
      id: '/_authenticated/worker/my-profile/reviews/'
      path: '/my-profile/reviews'
      fullPath: '/worker/my-profile/reviews'
      preLoaderRoute: typeof AuthenticatedWorkerMyProfileReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-profile/details/': {
      id: '/_authenticated/worker/my-profile/details/'
      path: '/my-profile/details'
      fullPath: '/worker/my-profile/details'
      preLoaderRoute: typeof AuthenticatedWorkerMyProfileDetailsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-applications/past/': {
      id: '/_authenticated/worker/my-applications/past/'
      path: '/my-applications/past'
      fullPath: '/worker/my-applications/past'
      preLoaderRoute: typeof AuthenticatedWorkerMyApplicationsPastIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-applications/active/': {
      id: '/_authenticated/worker/my-applications/active/'
      path: '/my-applications/active'
      fullPath: '/worker/my-applications/active'
      preLoaderRoute: typeof AuthenticatedWorkerMyApplicationsActiveIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-applications/$taskId/': {
      id: '/_authenticated/worker/my-applications/$taskId/'
      path: '/my-applications/$taskId'
      fullPath: '/worker/my-applications/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkerMyApplicationsTaskIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/dashboard/payments/': {
      id: '/_authenticated/worker/dashboard/payments/'
      path: '/dashboard/payments'
      fullPath: '/worker/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedWorkerDashboardPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/employer/my-proflie/reviews/': {
      id: '/_authenticated/employer/my-proflie/reviews/'
      path: '/my-proflie/reviews'
      fullPath: '/employer/my-proflie/reviews'
      preLoaderRoute: typeof AuthenticatedEmployerMyProflieReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-proflie/payments/': {
      id: '/_authenticated/employer/my-proflie/payments/'
      path: '/my-proflie/payments'
      fullPath: '/employer/my-proflie/payments'
      preLoaderRoute: typeof AuthenticatedEmployerMyProfliePaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-proflie/details/': {
      id: '/_authenticated/employer/my-proflie/details/'
      path: '/my-proflie/details'
      fullPath: '/employer/my-proflie/details'
      preLoaderRoute: typeof AuthenticatedEmployerMyProflieDetailsIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/worker/own-tasks/waiting-approval/$taskId': {
      id: '/_authenticated/worker/own-tasks/waiting-approval/$taskId'
      path: '/own-tasks/waiting-approval/$taskId'
      fullPath: '/worker/own-tasks/waiting-approval/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/own-tasks/to-do/$taskId': {
      id: '/_authenticated/worker/own-tasks/to-do/$taskId'
      path: '/own-tasks/to-do/$taskId'
      fullPath: '/worker/own-tasks/to-do/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkerOwnTasksToDoTaskIdRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/own-tasks/past/$taskId': {
      id: '/_authenticated/worker/own-tasks/past/$taskId'
      path: '/own-tasks/past/$taskId'
      fullPath: '/worker/own-tasks/past/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkerOwnTasksPastTaskIdRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-profile/reviews/$reviewId': {
      id: '/_authenticated/worker/my-profile/reviews/$reviewId'
      path: '/my-profile/reviews/$reviewId'
      fullPath: '/worker/my-profile/reviews/$reviewId'
      preLoaderRoute: typeof AuthenticatedWorkerMyProfileReviewsReviewIdRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-profile/details/edit': {
      id: '/_authenticated/worker/my-profile/details/edit'
      path: '/my-profile/details/edit'
      fullPath: '/worker/my-profile/details/edit'
      preLoaderRoute: typeof AuthenticatedWorkerMyProfileDetailsEditRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-applications/$taskId/task-details': {
      id: '/_authenticated/worker/my-applications/$taskId/task-details'
      path: '/my-applications/$taskId/task-details'
      fullPath: '/worker/my-applications/$taskId/task-details'
      preLoaderRoute: typeof AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/my-applications/$taskId/application-details': {
      id: '/_authenticated/worker/my-applications/$taskId/application-details'
      path: '/my-applications/$taskId/application-details'
      fullPath: '/worker/my-applications/$taskId/application-details'
      preLoaderRoute: typeof AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/worker/dashboard/payments/$paymentTransactionId': {
      id: '/_authenticated/worker/dashboard/payments/$paymentTransactionId'
      path: '/dashboard/payments/$paymentTransactionId'
      fullPath: '/worker/dashboard/payments/$paymentTransactionId'
      preLoaderRoute: typeof AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRouteImport
      parentRoute: typeof AuthenticatedWorkerRoute
    }
    '/_authenticated/employer/my-proflie/reviews/$reviewId': {
      id: '/_authenticated/employer/my-proflie/reviews/$reviewId'
      path: '/my-proflie/reviews/$reviewId'
      fullPath: '/employer/my-proflie/reviews/$reviewId'
      preLoaderRoute: typeof AuthenticatedEmployerMyProflieReviewsReviewIdRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-proflie/payments/$paymentId': {
      id: '/_authenticated/employer/my-proflie/payments/$paymentId'
      path: '/my-proflie/payments/$paymentId'
      fullPath: '/employer/my-proflie/payments/$paymentId'
      preLoaderRoute: typeof AuthenticatedEmployerMyProfliePaymentsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-proflie/details/edit': {
      id: '/_authenticated/employer/my-proflie/details/edit'
      path: '/my-proflie/details/edit'
      fullPath: '/employer/my-proflie/details/edit'
      preLoaderRoute: typeof AuthenticatedEmployerMyProflieDetailsEditRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-tasks/$taskId/tsx/': {
      id: '/_authenticated/employer/my-tasks/$taskId/tsx/'
      path: '/my-tasks/$taskId/tsx'
      fullPath: '/employer/my-tasks/$taskId/tsx'
      preLoaderRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-tasks/$taskId/tsx/details/': {
      id: '/_authenticated/employer/my-tasks/$taskId/tsx/details/'
      path: '/my-tasks/$taskId/tsx/details'
      fullPath: '/employer/my-tasks/$taskId/tsx/details'
      preLoaderRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-tasks/$taskId/tsx/applcations/': {
      id: '/_authenticated/employer/my-tasks/$taskId/tsx/applcations/'
      path: '/my-tasks/$taskId/tsx/applcations'
      fullPath: '/employer/my-tasks/$taskId/tsx/applcations'
      preLoaderRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-tasks/$taskId/tsx/details/edit': {
      id: '/_authenticated/employer/my-tasks/$taskId/tsx/details/edit'
      path: '/my-tasks/$taskId/tsx/details/edit'
      fullPath: '/employer/my-tasks/$taskId/tsx/details/edit'
      preLoaderRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/my-tasks/$taskId/tsx/applcations/$username': {
      id: '/_authenticated/employer/my-tasks/$taskId/tsx/applcations/$username'
      path: '/my-tasks/$taskId/tsx/applcations/$username'
      fullPath: '/employer/my-tasks/$taskId/tsx/applcations/$username'
      preLoaderRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
  }
}

interface AuthenticatedEmployerRouteChildren {
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
  AuthenticatedEmployerCreateTaskJobOfferRoute: typeof AuthenticatedEmployerCreateTaskJobOfferRoute
  AuthenticatedEmployerCreateTaskPublicTaskRoute: typeof AuthenticatedEmployerCreateTaskPublicTaskRoute
  AuthenticatedEmployerCreateTaskIndexRoute: typeof AuthenticatedEmployerCreateTaskIndexRoute
  AuthenticatedEmployerMyProflieIndexRoute: typeof AuthenticatedEmployerMyProflieIndexRoute
  AuthenticatedEmployerMyTasksIndexRoute: typeof AuthenticatedEmployerMyTasksIndexRoute
  AuthenticatedEmployerMyProflieDetailsEditRoute: typeof AuthenticatedEmployerMyProflieDetailsEditRoute
  AuthenticatedEmployerMyProfliePaymentsPaymentIdRoute: typeof AuthenticatedEmployerMyProfliePaymentsPaymentIdRoute
  AuthenticatedEmployerMyProflieReviewsReviewIdRoute: typeof AuthenticatedEmployerMyProflieReviewsReviewIdRoute
  AuthenticatedEmployerMyProflieDetailsIndexRoute: typeof AuthenticatedEmployerMyProflieDetailsIndexRoute
  AuthenticatedEmployerMyProfliePaymentsIndexRoute: typeof AuthenticatedEmployerMyProfliePaymentsIndexRoute
  AuthenticatedEmployerMyProflieReviewsIndexRoute: typeof AuthenticatedEmployerMyProflieReviewsIndexRoute
  AuthenticatedEmployerMyTasksTaskIdTsxIndexRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxIndexRoute
  AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRoute
  AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRoute
  AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRoute
  AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRoute: typeof AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRoute
}

const AuthenticatedEmployerRouteChildren: AuthenticatedEmployerRouteChildren = {
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
  AuthenticatedEmployerCreateTaskJobOfferRoute:
    AuthenticatedEmployerCreateTaskJobOfferRoute,
  AuthenticatedEmployerCreateTaskPublicTaskRoute:
    AuthenticatedEmployerCreateTaskPublicTaskRoute,
  AuthenticatedEmployerCreateTaskIndexRoute:
    AuthenticatedEmployerCreateTaskIndexRoute,
  AuthenticatedEmployerMyProflieIndexRoute:
    AuthenticatedEmployerMyProflieIndexRoute,
  AuthenticatedEmployerMyTasksIndexRoute:
    AuthenticatedEmployerMyTasksIndexRoute,
  AuthenticatedEmployerMyProflieDetailsEditRoute:
    AuthenticatedEmployerMyProflieDetailsEditRoute,
  AuthenticatedEmployerMyProfliePaymentsPaymentIdRoute:
    AuthenticatedEmployerMyProfliePaymentsPaymentIdRoute,
  AuthenticatedEmployerMyProflieReviewsReviewIdRoute:
    AuthenticatedEmployerMyProflieReviewsReviewIdRoute,
  AuthenticatedEmployerMyProflieDetailsIndexRoute:
    AuthenticatedEmployerMyProflieDetailsIndexRoute,
  AuthenticatedEmployerMyProfliePaymentsIndexRoute:
    AuthenticatedEmployerMyProfliePaymentsIndexRoute,
  AuthenticatedEmployerMyProflieReviewsIndexRoute:
    AuthenticatedEmployerMyProflieReviewsIndexRoute,
  AuthenticatedEmployerMyTasksTaskIdTsxIndexRoute:
    AuthenticatedEmployerMyTasksTaskIdTsxIndexRoute,
  AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRoute:
    AuthenticatedEmployerMyTasksTaskIdTsxApplcationsUsernameRoute,
  AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRoute:
    AuthenticatedEmployerMyTasksTaskIdTsxDetailsEditRoute,
  AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRoute:
    AuthenticatedEmployerMyTasksTaskIdTsxApplcationsIndexRoute,
  AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRoute:
    AuthenticatedEmployerMyTasksTaskIdTsxDetailsIndexRoute,
}

const AuthenticatedEmployerRouteWithChildren =
  AuthenticatedEmployerRoute._addFileChildren(
    AuthenticatedEmployerRouteChildren,
  )

interface AuthenticatedWorkerRouteChildren {
  AuthenticatedWorkerIndexRoute: typeof AuthenticatedWorkerIndexRoute
  AuthenticatedWorkerTasksTaskIdRoute: typeof AuthenticatedWorkerTasksTaskIdRoute
  AuthenticatedWorkerDashboardIndexRoute: typeof AuthenticatedWorkerDashboardIndexRoute
  AuthenticatedWorkerMyApplicationsIndexRoute: typeof AuthenticatedWorkerMyApplicationsIndexRoute
  AuthenticatedWorkerMyProfileIndexRoute: typeof AuthenticatedWorkerMyProfileIndexRoute
  AuthenticatedWorkerOwnTasksIndexRoute: typeof AuthenticatedWorkerOwnTasksIndexRoute
  AuthenticatedWorkerTasksIndexRoute: typeof AuthenticatedWorkerTasksIndexRoute
  AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRoute: typeof AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRoute
  AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRoute: typeof AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRoute
  AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRoute: typeof AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRoute
  AuthenticatedWorkerMyProfileDetailsEditRoute: typeof AuthenticatedWorkerMyProfileDetailsEditRoute
  AuthenticatedWorkerMyProfileReviewsReviewIdRoute: typeof AuthenticatedWorkerMyProfileReviewsReviewIdRoute
  AuthenticatedWorkerOwnTasksPastTaskIdRoute: typeof AuthenticatedWorkerOwnTasksPastTaskIdRoute
  AuthenticatedWorkerOwnTasksToDoTaskIdRoute: typeof AuthenticatedWorkerOwnTasksToDoTaskIdRoute
  AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRoute: typeof AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRoute
  AuthenticatedWorkerDashboardPaymentsIndexRoute: typeof AuthenticatedWorkerDashboardPaymentsIndexRoute
  AuthenticatedWorkerMyApplicationsTaskIdIndexRoute: typeof AuthenticatedWorkerMyApplicationsTaskIdIndexRoute
  AuthenticatedWorkerMyApplicationsActiveIndexRoute: typeof AuthenticatedWorkerMyApplicationsActiveIndexRoute
  AuthenticatedWorkerMyApplicationsPastIndexRoute: typeof AuthenticatedWorkerMyApplicationsPastIndexRoute
  AuthenticatedWorkerMyProfileDetailsIndexRoute: typeof AuthenticatedWorkerMyProfileDetailsIndexRoute
  AuthenticatedWorkerMyProfileReviewsIndexRoute: typeof AuthenticatedWorkerMyProfileReviewsIndexRoute
  AuthenticatedWorkerOwnTasksPastIndexRoute: typeof AuthenticatedWorkerOwnTasksPastIndexRoute
  AuthenticatedWorkerOwnTasksToDoIndexRoute: typeof AuthenticatedWorkerOwnTasksToDoIndexRoute
  AuthenticatedWorkerOwnTasksWaitingApprovalIndexRoute: typeof AuthenticatedWorkerOwnTasksWaitingApprovalIndexRoute
}

const AuthenticatedWorkerRouteChildren: AuthenticatedWorkerRouteChildren = {
  AuthenticatedWorkerIndexRoute: AuthenticatedWorkerIndexRoute,
  AuthenticatedWorkerTasksTaskIdRoute: AuthenticatedWorkerTasksTaskIdRoute,
  AuthenticatedWorkerDashboardIndexRoute:
    AuthenticatedWorkerDashboardIndexRoute,
  AuthenticatedWorkerMyApplicationsIndexRoute:
    AuthenticatedWorkerMyApplicationsIndexRoute,
  AuthenticatedWorkerMyProfileIndexRoute:
    AuthenticatedWorkerMyProfileIndexRoute,
  AuthenticatedWorkerOwnTasksIndexRoute: AuthenticatedWorkerOwnTasksIndexRoute,
  AuthenticatedWorkerTasksIndexRoute: AuthenticatedWorkerTasksIndexRoute,
  AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRoute:
    AuthenticatedWorkerDashboardPaymentsPaymentTransactionIdRoute,
  AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRoute:
    AuthenticatedWorkerMyApplicationsTaskIdApplicationDetailsRoute,
  AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRoute:
    AuthenticatedWorkerMyApplicationsTaskIdTaskDetailsRoute,
  AuthenticatedWorkerMyProfileDetailsEditRoute:
    AuthenticatedWorkerMyProfileDetailsEditRoute,
  AuthenticatedWorkerMyProfileReviewsReviewIdRoute:
    AuthenticatedWorkerMyProfileReviewsReviewIdRoute,
  AuthenticatedWorkerOwnTasksPastTaskIdRoute:
    AuthenticatedWorkerOwnTasksPastTaskIdRoute,
  AuthenticatedWorkerOwnTasksToDoTaskIdRoute:
    AuthenticatedWorkerOwnTasksToDoTaskIdRoute,
  AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRoute:
    AuthenticatedWorkerOwnTasksWaitingApprovalTaskIdRoute,
  AuthenticatedWorkerDashboardPaymentsIndexRoute:
    AuthenticatedWorkerDashboardPaymentsIndexRoute,
  AuthenticatedWorkerMyApplicationsTaskIdIndexRoute:
    AuthenticatedWorkerMyApplicationsTaskIdIndexRoute,
  AuthenticatedWorkerMyApplicationsActiveIndexRoute:
    AuthenticatedWorkerMyApplicationsActiveIndexRoute,
  AuthenticatedWorkerMyApplicationsPastIndexRoute:
    AuthenticatedWorkerMyApplicationsPastIndexRoute,
  AuthenticatedWorkerMyProfileDetailsIndexRoute:
    AuthenticatedWorkerMyProfileDetailsIndexRoute,
  AuthenticatedWorkerMyProfileReviewsIndexRoute:
    AuthenticatedWorkerMyProfileReviewsIndexRoute,
  AuthenticatedWorkerOwnTasksPastIndexRoute:
    AuthenticatedWorkerOwnTasksPastIndexRoute,
  AuthenticatedWorkerOwnTasksToDoIndexRoute:
    AuthenticatedWorkerOwnTasksToDoIndexRoute,
  AuthenticatedWorkerOwnTasksWaitingApprovalIndexRoute:
    AuthenticatedWorkerOwnTasksWaitingApprovalIndexRoute,
}

const AuthenticatedWorkerRouteWithChildren =
  AuthenticatedWorkerRoute._addFileChildren(AuthenticatedWorkerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRouteWithChildren
  AuthenticatedWorkerRoute: typeof AuthenticatedWorkerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEmployerRoute: AuthenticatedEmployerRouteWithChildren,
  AuthenticatedWorkerRoute: AuthenticatedWorkerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutServiceRoute: typeof PublicAboutServiceRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicPricingRoute: typeof PublicPricingRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutServiceRoute: PublicAboutServiceRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicPricingRoute: PublicPricingRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
